---
title: "Hackathon"
description: "A training opportunity in data analytics"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Setup

The Center for Cognitive and Decision Sciences (CDS) coordinates collaborative projects involving CDS members and MSc students associated with the center as part of its mission to provide training in data analytics (see [cds.unibas.ch](https://psychologie.unibas.ch/de/fakultaet/abteilungen/cognitive-and-decision-sciences-305/msc-project/) for more information). 

Dr. Dirk Wulff and Prof. Dr. Rui Mata supervised the project and Dr. Dirk Wulff conducted all data preprocessing. The project consists of a series of planning [sessions](https://psychologie.unibas.ch/de/fakultaet/abteilungen/cognitive-and-decision-sciences-305/events/) and two collaborative [hackathons](hackathon.html) described below. Resources related to the hackathons are available on this <a href="https://github.com/cdsbasel/Diversity_hackathon"><b>Github repository</b></a>. 

## Hackathons 

### Part I - Data Visualization (October 14th, 2021)

#### Goal

The goal of the first hackathon session is to produce different visualizations illustrating...

1. diversity gaps (gender, age, nationality) in number of publications over time (2000-2020) 

2. assess the role of moderators on the different diversity gaps, such as the role of...
  - organizational units 
  - authorship type (e.g., single, first, last)
  - publication type (e.g., journal articles, books, conference proceedings)

#### Rules

1. Each group creates and works in a single R script that is given a unique name by the group, e.g., a group pseudonym (to avoid conflicts with the other groups' script files). The script file is stored in `1_code`. See code template including the placeholder `GROUPPSEUDONYM`.
2. Each group creates XXX `.pdf` figure files in the `2_figures` folder. Figure files also must receive a suffix identifying the group. See example figure. 
3. Pull before you Push.

### Part II - Reporting (October 20th, 2021)


#### Goal

The goal of the second hackathon part is to produce a report based on the visualizations produced in the first hackathon using R Markdown. 

#### Rules

1. Each group creates and works in a single R Markdown document that is given a unique name by the group. 

2. Pull before you Push.

